# Generated by Django 4.0.1 on 2022-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.TextField()),
                ('mName', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('lName', models.TextField()),
                ('bDate', models.DateTimeField()),
                ('phone', models.PositiveIntegerField()),
                ('email', models.TextField()),
                ('sex', models.TextField()),
                ('bloodType', models.TextField()),
            ],
        ),
    ]
