# Generated by Django 4.0.1 on 2022-01-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtopms', models.TextField(verbose_name='Symptopms')),
                ('condition', models.TextField(verbose_name='Conditions')),
                ('prescription', models.TextField(verbose_name='Prescription')),
                ('date', models.DateField(verbose_name='History Date')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('blood_type', models.CharField(max_length=2, verbose_name='Blood Type')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.condition', verbose_name='Condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Patient')),
            ],
        ),
    ]
