# Generated by Django 4.0.1 on 2022-02-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtopms', models.TextField(verbose_name='Symptopms')),
                ('condition', models.TextField(verbose_name='Conditions')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Prescription')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='History Date')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('blood_type', models.CharField(blank=True, max_length=2, null=True, verbose_name='Blood Type')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='From Time')),
                ('to_time', models.TimeField(verbose_name='To Time')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.condition', verbose_name='Condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.schedule', verbose_name='Schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
