# Generated by Django 4.0.1 on 2022-01-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Entry date and time')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_date', models.DateField(verbose_name='Birth Date')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.schedule', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
