# Generated by Django 3.2.9 on 2022-01-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_queue_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='conditons',
            new_name='conditions',
        ),
    ]
