# Generated by Django 4.0.1 on 2022-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
    ]
